import '../lib/all.rb'


file 'words.txt' => :dataset do |t|
  sh "echo '<null>' > #{t.name}"
  sh "echo '<unknown>' >> #{t.name}"
  sh "cat #{DATASET_DIR}/aclImdb/imdb.vocab >> #{t.name}"
end


task :default => %i(dataset words.txt) do |t|
  sh %W(python main.py
        --num_classes 2
        --word_file #{t.sources[1]}
        --train_file '#{TRAIN_FILE}'
        --eval_file '#{EVAL_FILE}'
        --train_steps 1000
        --eval_steps 50
        --batch_size 64
        --min_eval_frequency 10
  ).join(' ')
end
