require_relative '../lib/config'
import '../lib/all.rb'


task :default => [:dataset, WORD_FILE] do |t|
  sh %W(python main.py
        --num_classes 2
        --word_file #{t.sources[1]}
        --train_file '#{TRAIN_FILE}'
        --eval_file '#{EVAL_FILE}'
        --train_steps 20
        --eval_steps 20
        --batch_size 4
  ).join(' ')
end
